
package lt.viko.eif.neinoris.students.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentsPort", targetNamespace = "http://spring.io/guides/gs-producing-web-service")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentsPort {


    /**
     * 
     * @param getStudentRequest
     * @return
     *     returns lt.viko.eif.neinoris.sendaikciai.client.GetStudentResponse
     */
    @WebMethod
    @WebResult(name = "getStudentResponse", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getStudentResponse")
    public GetStudentResponse getStudent(
        @WebParam(name = "getStudentRequest", targetNamespace = "http://spring.io/guides/gs-producing-web-service", partName = "getStudentRequest")
        GetStudentRequest getStudentRequest);

}
